pub struct SchoolInfo {
    pub name: &'static str,
    pub url: &'static str,
}

pub const SCHOOLS: &[SchoolInfo] = &[
    SchoolInfo { name: "北京大学", url: "http://www.pku.edu.cn/" },
    SchoolInfo { name: "清华大学", url: "http://www.tsinghua.edu.cn/" },
    SchoolInfo { name: "中国人民大学", url: "http://www.ruc.edu.cn/" },
    SchoolInfo { name: "北京师范大学", url: "http://www.bnu.edu.cn/" },
    SchoolInfo { name: "北京航空航天大学", url: "http://www.buaa.edu.cn/" },
    SchoolInfo { name: "北京理工大学", url: "http://www.bit.edu.cn/" },
    SchoolInfo { name: "中国农业大学", url: "http://www.cau.edu.cn/" },
    SchoolInfo { name: "中央民族大学", url: "http://www.muc.edu.cn/" },
    SchoolInfo { name: "中国科学院大学", url: "http://www.ucas.ac.cn/" },
    SchoolInfo { name: "复旦大学", url: "http://www.fudan.edu.cn/" },
    SchoolInfo { name: "上海交通大学", url: "http://www.sjtu.edu.cn/" },
    SchoolInfo { name: "同济大学", url: "http://www.tongji.edu.cn/" },
    SchoolInfo { name: "华东师范大学", url: "http://www.ecnu.edu.cn/" },
    SchoolInfo { name: "上海财经大学", url: "http://www.shufe.edu.cn/" },
    SchoolInfo { name: "南开大学", url: "http://www.nankai.edu.cn/" },
    SchoolInfo { name: "天津大学", url: "http://www.tju.edu.cn/" },
    SchoolInfo { name: "重庆大学", url: "http://www.cqu.edu.cn/" },
    SchoolInfo { name: "南京大学", url: "http://www.nju.edu.cn/" },
    SchoolInfo { name: "东南大学", url: "http://www.seu.edu.cn/" },
    SchoolInfo { name: "南京航空航天大学", url: "http://www.nuaa.edu.cn/" },
    SchoolInfo { name: "浙江大学", url: "http://www.zju.edu.cn/" },
    SchoolInfo { name: "中国科学技术大学", url: "http://www.ustc.edu.cn/" },
    SchoolInfo { name: "武汉大学", url: "http://www.whu.edu.cn/" },
    SchoolInfo { name: "华中科技大学", url: "http://www.hust.edu.cn/" },
    SchoolInfo { name: "中南大学", url: "http://www.csu.edu.cn/" },
    SchoolInfo { name: "湖南大学", url: "http://www.hunu.edu.cn/" },
    SchoolInfo { name: "中山大学", url: "http://www.sysu.edu.cn/" },
    SchoolInfo { name: "华南理工大学", url: "http://www.scut.edu.cn/" },
    SchoolInfo { name: "四川大学", url: "http://www.scu.edu.cn/" },
    SchoolInfo { name: "电子科技大学", url: "http://www.uestc.edu.cn/" },
    SchoolInfo { name: "西安交通大学", url: "http://www.xjtu.edu.cn/" },
    SchoolInfo { name: "西北工业大学", url: "http://www.nwpu.edu.cn/" },
    SchoolInfo { name: "兰州大学", url: "http://www.lzu.edu.cn/" },
];
